name: Terraform Apigee & LB

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Componente alvo (apigee ou lb)"
        required: true
        type: choice
        options:
          - apigee
          - lb
      environment:
        description: "Org alvo (nonprod ou prod)"
        required: true
        type: choice
        options:
          - nonprod
          - prod
      action:
        description: "Ação do Terraform"
        required: true
        type: choice
        options:
          - plan
          - apply

env:
  TF_APIGEE_BASE: tf-gcp-iac-infra-apigee/environments
  TF_LB_BASE: tf-gcp-iac-infra-apigee/environments-lb

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.0"

      # TODO: ajustar para o seu WIF / SA
      - name: Autenticar no GCP via Workload Identity
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Definir diretório de trabalho
        id: setdir
        run: |
          if [ "${{ github.event.inputs.component }}" = "apigee" ]; then
            echo "TF_WORKING_DIR=${{ env.TF_APIGEE_BASE }}/${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          else
            echo "TF_WORKING_DIR=${{ env.TF_LB_BASE }}/${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          fi

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false

      - name: Terraform apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false -auto-approve
