name: Terraform Apigee (simple)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Org alvo (nonprod ou prod)"
        required: true
        type: choice
        options:
          - nonprod
          - prod
      action:
        description: "Ação do Terraform"
        required: true
        type: choice
        options:
          - plan
          - apply

env:
  TF_WORKING_BASE: tf-gcp-iac-infra-apigee/environments

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth GCP via Service Account JSON
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_BASE }}/${{ github.event.inputs.environment }}
        run: terraform init -input=false

      - name: Terraform plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: ${{ env.TF_WORKING_BASE }}/${{ github.event.inputs.environment }}
        run: terraform plan -input=false

      - name: Terraform apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ${{ env.TF_WORKING_BASE }}/${{ github.event.inputs.environment }}
        run: terraform apply -input=false -auto-approve
